server:
  port: 8081

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000 #毫秒
    publisher-confirms: true #支持发布确认（确认消息是否发送到交换器）
    publisher-returns: true #支持发布返回（确认消息没有存入到相应的队列）
    cache:
      channel:
        size: 1
    listener:
      simple:
        acknowledge-mode: manual #消息接收手动ack确认

xxl:
  job:
    admin-addresses: http://127.0.0.1:7777/xxl-job-admin
    access-token: SEC9f4390e8c897e
    executor-ip:
    executor-port: 8002
    executor-log-retention-days: 7

#自定义自动配置参数
boot:
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 10000
    maxTotal: 100
    maxIdle: 10
    minIdle: 0
  aliYun:
    log:
      log-store: prod_boot
    ding-talk:
      web-hook: https://oapi.dingtalk.com/robot/send?access_token=da82d4099a3f2515480f35210cc17dd02f315e99537d29cd3de1a751e551b670
      secret: SECa17df9ae897fb39d525a173c47dcc93a6b01133fbb4bf3e659060cd4ed4539ea
swagger:
  enable: false

aliPay:
  payGateWay: XX


