#server
server:
  session:
    timeout: 3600 #秒
  context-path: /

#spring
spring:
  profiles:
    active: dev
  aop:
    auto: true # Add @EnableAspectJAutoProxy
    proxy-target-class: false
  http:
    #编码
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    #MultipartResolver
    multipart:
      enabled: false #关闭自带multipartResolver,否则commonsMultipartResolver解析会得不到数据
  mail:
    host: smtp.163.com
    port: 465 #设置端口465，因为阿里25端口默认禁用
    username: xwb1ng@163.com
    password: xwbing000111 #邮箱设置里获取的授权码
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true #授权
          socketFactory: #因为阿里云服务器25端口默认加密，需要改用sl加密465端口发送邮件
            class: javax.net.ssl.SSLSocketFactory #SSL证书Socket工厂(指定Socket工厂)
            port: 465 #设置ssl端口
            fallback: true #当指定的socket工厂创建socket失败时，是否使用默认的socket工厂创建
          starttls: #对纯文本通信协议的扩展。它提供一种方式将纯文本连接升级为加密连接（TLS或SSL），而不是另外使用一个端口作加密通信。
            enable: true
            required: true
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
        dialect: org.hibernate.dialect.MySQL5Dialect

#mybatis
#mybatis:
#  mapper-locations: #classpath:mapper/**/*.xml
#  type-aliases-package: #com.xwbing.domain.entity
#  config-location: # classpath:mybatisConfig.xml

pagehelper:
  helper-dialect: mysql

#log
logging:
  config: classpath:log4j2.xml

#自定义自动配置参数
boot:
  redis:
    prefix: boot_
    enabled: true
  #阿里云配置
  aliYun:
    enabled: true
    log:
      access-id: xxx
      access-key: xxx
      endpoint: cn-hangzhou.log.aliyuncs.com
      project: boot-api
      topic: boot_moddule

#切面自动配置参数
aspect:
  service-pointcut: execution(public * com.xwbing.service..*.*(..))

xxl:
  job:
    enabled: true
    executor-app-name: boot
    executor-log-path: logs/jobhandler