server:
  port: 8080

spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    connection-timeout: 60000
    publisher-confirms: true
    publisher-returns: true
    cache:
      channel:
        size: 1
    listener:
      simple:
        acknowledge-mode: manual

xxl:
  job:
    admin-addresses: http://127.0.0.1:7777/xxl-job-admin
    access-token: SEC9f4390e8c897e
    executor-ip:
    executor-port: 8001
    executor-log-retention-days: 3

boot:
  redis:
    host: 127.0.0.1
    port: 6379
    password: xwbing
    timeout: 10000
    maxTotal: 50
    maxIdle: 5
    minIdle: 0
  aliYun:
    log:
      log-store: test_lease
    ding-talk:
      web-hook: https://oapi.dingtalk.com/robot/send?access_token=f41b013832ca349f45cabce7dd7e64b19f3e1aabc4414d71a1e9ee050d65e141
      secret: SEC9f4390e8c897e118ab487b0ed5874100a7693920eb87e9a968ee8129b0874e3f

